services:
  frontend:
    image: naveenchowdary577/astrix-frontend:1.3.0
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5000}
    ports:
      - "5173:5173"
    environment:
      PORT: 5173

  backend:
    image: naveenchowdary577/astrix-backend:1.3.0
    build:
      context: ./server
    ports:
      - "5000:5000"

    env_file:
      - ./server/.env
    environment:
      CLIENT_URL: ${CLIENT_URL:-http://localhost:5173}
      RL_LLM_API_URL: ${RL_LLM_API_URL:-}
